name = "FormalSeries"
uuid = "a55ae9b5-0907-4af6-81ab-c6ed2f8e0777"
authors = ["Alberto Ramos <alberto.ramos@ific.uv.es>"]
version = "1.5.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"

[extensions]
FormalSeriesChainRulesCoreExt = "ChainRulesCore"

[compat]
ChainRulesCore = "1"
julia = "1.11"